from typing import Any

class Scene:
  sceneName:str
  manager:Any # 임포트 에러 이슈
  updatable:bool

  def __init__(self): ...

  def render(self): ...
  def update(self): ...

  def _onPress(self, key): ...
  def _onRelease(self, key): ...
